version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
      - image: circleci/node:9.11
      - image: circleci/node:10.9
    working_directory: ~/repo
    steps:
      - run: npm install
      - run: npm test